
@host = http://localhost:3000

###
 
GET {{host}}/statuses
###
 
GET {{host}}/statuses/22345

###

POST {{host}}/statuses
Content-Type: application/json

{
    "name": "test",
    "board_id": 2,
    "position": 4
}

###
GET {{host}}/boards/2/statuses

###
DELETE {{host}}/statuses/13/delete
###

GET {{host}}/boards



###
GET {{host}}/boards/



###
POST {{host}}/boards
Content-Type: application/json

{
    "name": "test",
    "description": "test description"
}


###

PATCH {{host}}/boards/5
Content-Type: application/json

{
    "name": "updated",
    "description": "test description"
}

###
DELETE {{host}}/boards/5/delete 













